### PR TITLE
Rewrite stuff

### PR DESCRIPTION
**Pull request by SheIITear**
Rewrote stuff to make it cleaner and fixed some documentation.

### CODE REVIEW

**Review by TermuxHackz — APPROVED** [review]

**Review by TermuxHackz — APPROVED** [review]

**Review by TermuxHackz — APPROVED** [review]
Thanks for the change and documentation of README

**Review by TermuxHackz — CHANGES_REQUESTED** [review]
But I'll need to add the npm install prompt-sync since its imported module in the script.

**Comment by SheIITear** [comment]
It's already there.

**Review by blackbee05 — APPROVED** [review]
AnonCrypt.js

**Pull request merged**
